### ISSUE TITLE
[Documentation Amendment] Add an example with optional or different arguments to the command registration chapter

### ISSUE THREAD

**Issue by Minenash** [JorelAli/1.13-Command-API#101]
**Chapter Number**
Chapter 3 (1st chapter of section 2):  Command Registration

**Section**
Wherever appropriate. 

**Amendment**
Add an example with optional or different arguments. Like
```
/kill
/kill <player>
```
This example is already in the permissions section, but unless they read that section, I'd be fair to assume, because of how the doc examples are, that this type of registration might not be possible with the lib.

**Comment by JorelAli** [comment]
Can do - probably would come under section 5, since it's argument related.
