### ISSUE TITLE
Error when adding using gradle

### ISSUE THREAD

**Issue by Ricky12Awesome** [JorelAli/1.13-Command-API#103]
**CommandAPI version**
3.0

**Describe the bug**
When I add the depend to my gradle file it gives an error.

Here's a newly created project with just the depend added:
https://github.com/Ricky12Awesome/example-1.13CommandAPI

I've even tested this on another pc using that repo and gives the same error as well.

Don't know if this is an issue with gradle, since it only does with this depend and no others.
**Expected behavior**
No errors, just works like any other depend

**Comment by JorelAli** [comment]
Apparently, I had no idea how maven repositories work. This commit 6d723c1c72fa2cde06127a95b2a2f8327f71a019 should fix it - I was able to build your project after applying this commit!
