### ISSUE TITLE
Issues with 3.1 and 3.2 not getting jar from repo

### ISSUE THREAD

**Issue by Ricky12Awesome** [JorelAli/1.13-Command-API#109]
**CommandAPI version**: 3.1/3.2

**Describe the bug**:
When I add the dependency to my project, it doesn't download any jars specifically for `3.1` and `3.2`, `3.0` works fine
When trying to looks for the issue, it seems that the repo for `3.1` and `3.2` doesn't even contain any jars

Here's the repo I was testing this on: https://github.com/Ricky12Awesome/example-1.13CommandAPI

**Expected behavior**:
When adding the dependency it downloads the jars so you can actually use it

**Video**: https://streamable.com/r2tcn2 (Because it's just easier show this way)

**Comment by JorelAli** [comment]
Yup, can confirm I did not upload the jars. Will sort it out later today (within 12 hours)

**Comment by Ricky12Awesome** [comment]
Seems to work
![image](https://user-images.githubusercontent.com/29931568/86531433-c6e4cd00-be86-11ea-8560-cea2f254e560.png)

**Comment by JorelAli** [comment]
Fantastic. I've updated the documentation which now states to use `commandapi-core`
