### ISSUE TITLE
Add project as maven dependency?

### ISSUE THREAD

**Issue by DerpNerb** [JorelAli/1.13-Command-API#11]
Perhaps I'm asking a stupid question, but I want to add this project as a maven dependency, and I don't know how to do that.

I tried adding a local dependency on the jar, but then maven won't build it properly.
I want it to be a maven dependency because then it updates automatically without having to download a new jar for every release. 

I also tried adding it like this:       

```
<dependency>
            <groupId>io.github.jorelali</groupId>
            <artifactId>commandapi</artifactId>
            <version>1.3</version>
</dependency>
```

But that just tells me:
`Dependency 'io.github.jorelali:commandapi:1.3' not found.`

Any help please?

**Comment by JorelAli** [comment]
You're not being stupid, I haven't created my maven repo yet. I'll try and get it sorted in the next day or so.

**Comment by DerpNerb** [comment]
Ah okay thanks for the help 👍 
Keep up the good work!

**Comment by yannicklamprecht** [comment]
https://jitpack.io/#JorelAli/1.13-Command-API

You can try using this in the meantime.

**Comment by Combustible** [comment]
If you're willing to compile this plugin yourself, you can do this: 

- Open up pom.xml and put a unique version in there for development (for example 1.2-devbuild)
- Do a `maven clean install`. This will install the jar into your local maven repository on your user account (should work in both windows and Linux...)
- Add this to your dependencies section of pom.xml:
```
        <dependency>
            <groupId>io.github.jorelali</groupId>
            <artifactId>commandapi</artifactId>
            <version>1.2-devbuild</version>
            <scope>provided</scope>
        </dependency>
``` 

And it should work!

**Comment by JorelAli** [comment]
Created a Maven Repository here on Github:
```
<repository>
    <id>commandapi</id>
    <url>https://raw.githubusercontent.com/JorelAli/1.13-Command-API/mvn-repo/</url>
</repository>
```

```
<dependency>
    <groupId>io.github.jorelali</groupId>
    <artifactId>commandapi</artifactId>
    <version>1.4</version>
</dependency>
```

**Comment by Combustible** [comment]
Weirdly - if I give the repository the id `commandapi` it doesn't work. If I call it anything else (`jorelali`) it works fine.  ?????
