### ISSUE TITLE
Be able to run command from other plugin through CommandBlock

### ISSUE THREAD

**Issue by LeGraalo** [JorelAli/1.13-Command-API#111]
Hello, i'm trying to execute a command from a Spigot plugin through minecraft vanilla CommandBlock and some forum subjects recommend to use your CommandAPI, wich enable you to execute plugin command through CommandBlock. But i'don't know if your plugin really permit it.

To be clear , i'm trying to execute the command : `/luckperms user @p parent add mygroup` wich add the player to 'mygroup' permission group, through a CommandBlock. But LuckPerms being a Spigot plugin, it can't be executed through a CommandBlock. 

So i wish to know if your plugin really permit to create a command that run a command from another plugin, and if it could be executed from a CommandBlock ? And if yes, how can i do that ?

Thanks for your time.
(Sorry for my english ^^)

**Comment by JorelAli** [comment]
Hi, I'm not ignoring you.
The CommandAPI does provide a way to incorporate spigot plugins by [command conversion](https://www.jorel.dev/1.13-Command-API/3.1/conversion.html). I'll try to come up with a full example later today and will check that it works for you if you fancy.

**Comment by LeGraalo** [comment]
Thanks for your response. I've find to do what i wanted with the PSudoCommands plugin. Thanks anyway. ^^
