### ISSUE TITLE
Add API version to plugin.yml

### ISSUE THREAD

**Issue by Demozo** [JorelAli/1.13-Command-API#112]
Console is telling me:
```
[00:45:35 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
```

I believe this is because CommandAPI currently does not specify an api version evident by the following console message:
```
[00:45:39 WARN]: Legacy plugin CommandAPI v3.2 does not specify an api-version.
```

This can be resolved by adding `api-version: '1.13'` to the plugin.yml file, I believe this will also solve the issue of legacy Material support being enabled.

**Comment by JorelAli** [comment]
Can do. It's a very minor addition and it doesn't change anything about how the commandapi functions, so it's not a big priority.

I'll schedule this for v3.3 or v4.0
