### ISSUE TITLE
Cannot use API in Kotlin due to overload resolution

### ISSUE THREAD

**Issue by LewisTehMinerz** [JorelAli/1.13-Command-API#113]
**CommandAPI version**
3.2

**Minecraft version**
N/A

**Describe the bug**
The API's overloads prevent usage of the API in Kotlin due to ambiguity.

**My code**
This code reproduces the behavior:
```kotlin
CommandAPICommand("bancho")
    .executes { sender: CommandSender, args: Array<out Any> ->
        sender.sendMessage("Test!")
    }
```

**Expected behavior**
I can use this code fine with no issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/8019327/86802468-f7865b80-c06c-11ea-8ede-698d13a18be6.png)

**Comment by Ricky12Awesome** [comment]
You would need to do
```kotlin
CommandAPICommand("bancho")
  .executes(CommandExecutor { sender, args -> 
    // code
  } 
```
You can have a look at https://github.com/Ricky12Awesome/kpl/blob/master/kpl-core/src/me/ricky/kpl/core/command/ which has CommandDSL and CommandManager using this library

so you can just do
```kotlin
command("test") {
  arguments["number"] = IntegerArgument()

  executes {
    val number: Int by arguments

    sender.sendMessage(number.toString())
  }
}
```

**Comment by LewisTehMinerz** [comment]
Weird. I already tried that and Kotlin still didn't like it, but now it's working. Oh well.
