### ISSUE TITLE
Command without arguments

### ISSUE THREAD

**Issue by Marvmallow** [JorelAli/1.13-Command-API#12]
Don't know if this is is a thing or not, but I can't seem to figure out how to register a command that does not have any arguments, I know this API is all about using the new Brigadier formatting, but I'd like to be able to do something with the command when it does not have any arguments.

Currently the solution would be to register it with Spigot/Bukkit itself, but at least on my test environment it will then override the formatting from CommandAPI and default to tab completing a Player on the server and does not show the arguments of the command that I'm also registering with CommandAPI.

Adding to that registering the command with an empty LinkedHashMap will result in the message "An unexpected error occurred trying to execute that command"

**Comment by JorelAli** [comment]
According to [this commit](https://github.com/JorelAli/1.13-Command-API/commit/68798b7bcdec6c395a1d86bebef7c2b71d5f1621), it should allow an empty `LinkedHashMap`, or `null` and still register the command successfully. Could you show me the code you're using?

**Comment by JorelAli** [comment]
Interesting. I believe there may be an issue with overwriting arguments by having one command with an argument registered after a command without an argument. I'll research this issue further when I have more free time.

**Comment by JorelAli** [comment]
Thanks very much! I've solved the issue and released version 1.4 which has this issue patched.
