### ISSUE TITLE
Enhancement - a way to un-register (or replace) existing commands

### ISSUE THREAD

**Issue by Combustible** [JorelAli/1.13-Command-API#15]
Since you've done everything else everyone has asked for, here's one more to think about... :)

I'd like a way to un-register or replace an existing command. 

In my case I'd like to remove minecraft's default /effect command so that I can replace it with my own version. 

I've tested out just registering identical commands to the vanilla /effect, but it looks like the vanilla one takes precedence. For now I'm stuck with /customeffect.

This would also be useful for /reload - I'm not sure what happens when a plugin tries to register its own commands again... I assume based on this testing that the original-registered versions take precedence, which probably means using out-of-date objects from the original lambda closure.

**Comment by JorelAli** [comment]
Command unregistration now available from [this commit](https://github.com/JorelAli/1.13-Command-API/commit/828fab905a52d9792a77437148a247213ead79be)

Currently, the CommandAPI doesn't have any support for /reload, and re-registering commands causes lots of mayhem and nonsense. I plan to look into it at some time.
