### ISSUE TITLE
Enhancement - a way to shade the CommandAPI directly into the user plugin

### ISSUE THREAD

**Issue by Combustible** [JorelAli/1.13-Command-API#16]
This would be basically including the CommandAPI jar classes directly into the user's plugin. 

This would be handy for plugin developers that don't want to make people install CommandAPI separately. 

Another nice thing is that if you do for some reason have to break backwards compatibility for a particular API, it wouldn't totally toast a server using multiple different plugins that use this API. 

For example, with the current distribution: 
- Plugin A uses v400 with old API
- Plugin B uses v500 with new API
These two plugins could not co-exist because installing any version of CommandAPI wouldn't satisfy both. 

I'm pretty sure Maven can do this somehow... The tricky bit is making it so that each plugin gets its own copy of a particular version to use so that different versions can co-exist nicely. 

There may be technical reasons why this is not possible - but it looks like it should be since there is no configuration and nothing to speak of in the main plugin onEnable().

**Comment by JorelAli** [comment]
**Ideally, no developer should be using an old version of the API.** Each version should ideally have better improvement/features _(Just look at the differences between 1.3 and 1.4)_. Yeah, I see where you're coming from - shading it in would be nice, but take into account other various APIs out there (such as ProtocolLib, or Vault) which don't.

[This issue](https://github.com/JorelAli/1.13-Command-API/issues/17) actually comes into play here quite a bit. I currently have very little caching which would improve the more plugins use the API.

I don't think I want to go down the route of shading the CommandAPI into other plugins, however you did mention the fact that there's no configuration and that does seem like something to perhaps take advantage of at a later date if required.

**Comment by JorelAli** [comment]
After implementing NMS caching (from [this commit](https://github.com/JorelAli/1.13-Command-API/commit/f4a29f6f100cf7e8909444dc5cd3f26e41fa9d58#diff-f3cdea893dbb86be9dd1e703bcd1a65e)), **I've decided not to implement shading**. My reasoning is as follows:

The CommandAPI uses lots of reflection (as found in the SemiReflector class) to access the various NMS objects and CraftBukkit API directly. As stated in [this issue](https://github.com/JorelAli/1.13-Command-API/issues/17), a lack of caching resulted in bad performance, especially as the CommandAPI is using so much reflection. Caching only works well if lots of reflective calls are being used, however shading makes this caching worthless.

## Scenario

Say we have 3 plugins, _Plugin A_, _Plugin B_ and _Plugin C_ which all use the CommandAPI and have it shaded into their own plugins.

Say _Plugin A_ registers 3 commands, each using different Arguments, say `ChatColor`, `Enchantment` and `EntitySelector`.
_Plugin B_ also registers 3 more commands, each using different Arguments which are not used by _Plugin A_, say `Particle`, `Location` and `ItemStack`.

As these plugins use a shaded version of the CommandAPI, they would only be caching their respective arguments. (so _Plugin A_ caches `ChatColor`, `Enchantment` and `EntitySelector` and _Plugin B_ caches `Particle`, `Location` and `ItemStack`)

_Plugin C_ registers 2 commands with arguments `ChatColor` and `Particle`. It shares the same arguments as both plugins A and B, however it doesn't have them cached, so it caches the arguments by itself.

However, if everything used a local CommandAPI (i.e. didn't shade it into their respective plugins), they would all use arguments which have one shared cache by the CommandAPI, thus improving the performance of all plugins.

**Comment by JorelAli** [comment]
For completeness, this has been implemented in version 4.1.
