### ISSUE TITLE
Caching of NMS

### ISSUE THREAD

**Issue by yannicklamprecht** [JorelAli/1.13-Command-API#17]
It seems that you are not caching your NMS classes, fields and methods. This results in bad performance.

**Comment by JorelAli** [comment]
I'm aware, however all of this invocation normally occurs once during the start of the server's initialization. If you're getting really bad performance, there's something wrong with your computer.

But yeah, it's true. I'll keep that in mind.

**Comment by JorelAli** [comment]
NMS caching has been implemented in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/f4a29f6f100cf7e8909444dc5cd3f26e41fa9d58#diff-f3cdea893dbb86be9dd1e703bcd1a65e)
