### ISSUE TITLE
Make test code configurable

### ISSUE THREAD

**Issue by Combustible** [JorelAli/1.13-Command-API#18]
The test code is sometimes left in the main build - which is really a problem when it unregisters /gamemode. 

Rather than having to remember to comment it back out - can you make it only run if a setting in the config file is set?

**Comment by JorelAli** [comment]
Implemented in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/3e789fce49c2c875bc81a42637169467cce79b94). Also added config to create the output for the command dispatcher's register to help debug command generation (as opposed to having it hardcoded).

**Comment by Combustible** [comment]
Awesome, thank you!
