### ISSUE TITLE
ProxiedCommandSender via /execute callee/caller incorrect

### ISSUE THREAD

**Issue by Combustible** [JorelAli/1.13-Command-API#20]
Finally had a need to try out the new ProxiedCommandSender change. 

Tested against v1.5, compiled from source (at the v1.5 tag)

After noting the behavior wasn't quite right, I added some prints to see what was going on. 

Here is my test command
```
/execute as @p run mycustomcommand
```

I observe the following behavior when I look at what `sender` actually contains: 

When run as a player: 
Sender is a `org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer` (bad - should be ProxiedCommandSender)

When run as a command block: 
Sender is a `org.bukkit.craftbukkit.v1_13_R2.command.ProxiedNativeCommandSender` (good)
Sender.callee is a `org.bukkit.craftbukkit.v1_13_R2.command.CraftBlockCommandSender` (bad - should be Player)
sender.caller is a `org.bukkit.craftbukkit.v1_13_R2.command.CraftBlockCommandSender` (good)

When run as the console: 
Sender is a `org.bukkit.craftbukkit.v1_13_R2.command.ColouredConsoleSender` (bad - should be ProxiedCommandSender)

**Comment by JorelAli** [comment]
> When run as a player:
Sender is a `org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer` (bad - should be ProxiedCommandSender)

### Logically
* If you run this command as a player, which targets yourself, I think it's reasonable for it to be a regular Player as opposed to a ProxiedCommandSender. (This I can't fix - see below)
* If you run this command as a player, which targets another player, it should be a ProxiedCommandSender. (this I can fix)

### Code wise
If you run this command as a player, which targets yourself, it's impossible to determine whether you ran the command yourself or targeting yourself. For example, say I'm playing as `Skepter` ingame:
`/execute as @p[name=Skepter] run mycommand` and `/mycommand` both produce the exact same response ingame (either both are ProxiedCommandSenders or both are players).

In other news, everything else should be fixable. It's just impossible to determine who's who if you're executing commands to yourself.

**Comment by JorelAli** [comment]
Fixed the main issue in this [commit](https://github.com/JorelAli/1.13-Command-API/commit/663dc3299633382b9480a8e2b032e643a87814fa) - my cache implementation for NMS was broken.

As stated above, when you're executing the command as yourself, it'll not return a ProxiedCommandSender, whereas everything else should work lovely.

Thanks for pointing this out - I've been pulling my hair out about this issue.

**Comment by Combustible** [comment]
Awesome! Thanks for your hard work. Will try it out!
