### ISSUE TITLE
Incorrect maven repo URL

### ISSUE THREAD

**Issue by Combustible** [JorelAli/1.13-Command-API#22]
Took me entirely too long to realize that the reason I couldn't get the maven repo working was that the documentation has the wrong URL. It currently has this: 

```
https://raw.githubusercontent.com/JorelAli/1.13-Command-API/mvn-repo/
```

It should be this (based on where the files are located today): 
```
https://raw.githubusercontent.com/JorelAli/1.13-Command-API/mvn-repo/1.13CommandAPI/
```

**Comment by JorelAli** [comment]
Fixed issue in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/dea01cc80d48cd25bd0a494f5969642b330ed10c). Thanks again!
