### ISSUE TITLE
extra permission node "minecraft.command.<command>"

### ISSUE THREAD

**Issue by zedwick** [JorelAli/1.13-Command-API#25]
There seems to be an additional permission node registered for a command, unclear when or why as it showing up seems to be sporadic. The node is in the format "minecraft.command.<command>"

It seems to always appear when registering a command without a `PermissionNode` specified, and sometimes show up if I specify my own `PermissionNode` when registering the command. I am using LuckPerms' `/lp tree` command to list permission nodes, I have had one instance so far where "minecraft.command.<command>" node does not show up at first, but will appear in the tree later.

In all cases, the command will still complete despite the extra permission node being attached to the command, but I cannot use the command if I do not have this permission set for myself.

Using version 1.6 with Paper 1.13.2 build 444

**Comment by JorelAli** [comment]
Sorry it took so long for a response, this is by far the hardest bug I've tried to sort out and I still have not gotten close to a solution yet.

To answer to first query: Why the `minecraft.command.` node is added. Simply put, the CommandAPI is a wrapper for Brigadier. Brigadier is primarily used by Minecraft to register Vanilla Minecraft Commands. When Bukkit _(Craftbukkit/Spigot/PaperSpigot)_ registers a "vanilla" minecraft command, it automatically registers the permission node `minecraft.command.<commandName>` to that command.

Now, permissions are this tightly knit super unnecessarily complex topic where things get very hazy and it is really difficult to understand. I'm trying to create a "valid" workaround for the problem - There are some "cheap" workarounds which fix the problem (i.e. you can't run the command if you don't have the permission), but aren't "correct" in the sense that they have the perfect desired effect (i.e. tab complete doesn't occur if you don't have the permission etc. - which is handled internally by the server)

I'm still trying my very best to work on this issue, but I don't believe I'll be able to push out the desired bug fix in time for the next planned release of 1.7.

**Comment by JorelAli** [comment]
Alright! I finally made progress and found a way to fix the issue in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/2323ea4edc74dc2a83f2d125ccd4160df5b57bc2).

In this commit, _lots of the permission system was rewritten_ and _should_ have full support for permissions. I'll deal with sub-permissions in the relevant issue #26 instead of here.

Keep an eye out for the documentation when 1.7 is released which should cover the new syntax changes for permissions.
