### ISSUE TITLE
DynamicSuggestedArgument missing context about partially typed command

### ISSUE THREAD

**Issue by Combustible** [JorelAli/1.13-Command-API#27]
Have been playing with the very new DynamicSuggestedArgument some, and it has one odd quirk which makes it much less user friendly than other argument suggestion options. 

Minecraft isn't actually taking into account the characters you start typing for the suggestions. So for example if you have "alice" and "bob" as suggestions, if you start typing "bo", it calls the completer and asks for the completions - which returns "alice" and "bob". So minecraft returns possible completions "alice" and "bob" to the client. The problem is - "alice" is not a valid completion for "bo". So you get a dynamic list that contains a bunch of stuff you don't want, and it doesn't narrow down the more characters you type. 

I'm not sure if you can get at the client's partially completed string - but I bet you can. If so, can you pass that in as an argument to the functional interface? Then when I implement my dynamic completion callback I can look at the partial match and only supply back suggestions that match it.

Thanks!

**Comment by JorelAli** [comment]
After testing, I realise this also occurs with the `SuggestedStringArgument` as well. I'm now aware that it _is_ possible to (somewhat) get the partially completed string, however I believe that the CommandAPI should handle that entirely. In other words, the CommandAPI should handle the partial matching by itself and that shouldn't come down to the responsibility of the user.

It's true that passing the partially completed string back to the user allows them to handle the suggestions as they see fit, allowing very complex suggestions such as `@e` -> `@e[` -> `@e[limit=` etc. however you have to remember that the CommandAPI is a wrapper for Brigadier. Handling such complex suggestions isn't something I really fancy doing and if someone _does_ want to go the extra mile, they're more than welcome to use Brigadier itself. Trying to implement a wrapper for suggestions doesn't seem feasible at the moment - my aim with the CommandAPI is to "hide" Brigadier from the user.

I've fixed the issue in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/faa6613a61bc94df60d9893ade906452f3bfde9b) which implements the "standard" suggestion list.
