### ISSUE TITLE
[Enhancement] Set result and success of command

### ISSUE THREAD

**Issue by HielkePlugins** [JorelAli/1.13-Command-API#28]
Vanilla commands outputs whether the command has successfully executed or not. It also keeps outputs its result.

**Example:**
`/tp @a[name=Notch] @s`

This command will only be successfully run if there is a player named Notch in the world. Otherwise the success score will be 0. 

![2018-11-25_14 58 58](https://user-images.githubusercontent.com/42968178/48979953-b1140100-f0c2-11e8-8d18-b9516abd5118.png)

The success is always either 0 or 1. In the picture above it's 0, as there is no player named Notch online.

Vanilla commands also output their result, which can be more than 0 or 1.

**Example:**
![2018-11-25_15 01 30](https://user-images.githubusercontent.com/42968178/48979968-03552200-f0c3-11e8-907d-13b080fe6e36.png)
The success of this command is 1. The result is 35, as there are 35 entities in the world.

Right now, every commandAPI command will always be successfully run, so the success of every command will always be 1. The result is 1 too.

It would be awesome if we could do this with commandAPI commands too :D

**Comment by HielkePlugins** [comment]
Exactly how I figured it will work! Just like vanilla commands :)
Also it looks like I've made exactly the same command as you did: the random number command. :D

Right now I just have a String argument for a scoreboard objective, so it sets the output to the score of the callee. (Also a scoreboard argument type would rock!)

**Comment by HielkePlugins** [comment]
The scoreboard really isn't that complex!

First of all, to make testing easier you should use 
`/scoreboard objective setdisplay  sidebar <testobjective>`

That way you don't have to do `/scoreboard player list` every time you run a test command, as you can see it update in the sidebar.

**About the scoreboard:**

- It can only store integers
- Any entity can have a score
- Scoreboard objectives have to be a certain criteria.  'dummy' is what most people use, because the game won't set the score of this criteria itself. (Unlike criteria like 'health', which automatically update their score when a entity's health changes)

**The execute command:**

The awesome thing about the /execute command is that it allows for multiple sub commands.
It basically comes down to this this:

**/execute (sub command) (another sub command) (...) run (actual command)**

You can have as many (or as little) sub commands as you want. 

Store is such a sub command. You can only use store when using execute.
The only thing that matters to the store command is the actual command (after the **run**)

Vanilla commands **always** return their success and result. The `store` sub command then handles these values and stores them in some way (Can be scoreboard score, entity NBT, block NBT or bossbar)

**Example:**
`/execute store result score @s resultObjective store success score @s successObjective run say hi`

Here there are 2 store commands that both store something about the "say hi" command at the end. One stores the result, and one the success. 
In this example they both will always be 1, so let's take a look at another one:

`/execute store result score @s resultObjective store success score @s successObjective run execute if entity @e[type=creeper]`

The execute if is kind of a complicated command, but the important part is that it works as a test if it's after the run argument.

So, in this example the actual argument is `execute if entity @e[type=creeper]`, which basically checks for creeper entities. 

- If it find any creeper, your successObjective score will be one. 
- Your resultObjective score will be set to how many creepers are actually found.

Please let me know if there are things you don't understand :)

**Comment by JorelAli** [comment]
Thanks for the help - it's made a lot of misunderstandings very clear. I was completely unaware that the `/testfor` command had been removed!

After hours of programming, I've finally got a way for success values to return 0 or 1 (from [this commit](https://github.com/JorelAli/1.13-Command-API/commit/f966a025f4e14cc90549015117ece13cf4715d2a))!

The syntax is a little "eh", but still:

```java
CommandAPI.getInstance().register("failcmd", arguments, (sender, args) -> {
    if(/* Some condition */) {
        CommandAPI.fail("This creates a success of 0");
        return 0; // NB: See Developer's Note below
    } else {
        //Code here
        return 5 /* meaningful integer */;
    }
});
```

**Developer's Note**
The function `CommandAPI.fail()` prevents the `return 0;` code from actually running (it simply terminates the command at that point). Personally, I prefer this implementation rather than letting developers throw exceptions here and there - I think this is a cleaner alternative and hides the technicalities from other developers (to make the API as user friendly as possible).

**Comment by Combustible** [comment]
I definitely agree that the mechanism should not rely on throwing exceptions to return an error.

So, to be clear: 
- If your code returns a value, that will be the `result` of the command? And `success` will be set to 1
- If your code calls `CommandAPI.fail()`, `success` will be set to 0 and `value` will also be 0?

**Comment by Combustible** [comment]
I just looked at the implementation. I see that all fail() does is throw an exception - I was going to complain, but the more I looked at it the more it looks like that's what brigadier expects you to do? Weird, but I don't have any better ideas.

**Comment by HielkePlugins** [comment]
Looks awesome! Will you update the entity selector arguments too? So it gives a success of 0 when there's no entity found? That would be really helpful!

**Comment by JorelAli** [comment]
It just so happens to be your lucky day - it's already built in.

**Comment by HielkePlugins** [comment]
Yay! ^_^

**Comment by JorelAli** [comment]
I'm hoping to resolve the permissions bug of `minecraft.command.blah`  before the 1.7 release - I've finally found a potential fix for this pretty critical bug!
