### ISSUE TITLE
DynamicSuggestedStringArgument causes ClassCastException

### ISSUE THREAD

**Issue by HielkePlugins** [JorelAli/1.13-Command-API#31]
**Describe the bug**
The commandApi throws an ClassCastException when having one or multiple argument before a DynamicSuggestedStringArgument.  The error doesn't occur when using the LiteralArgument, but that's because it's not really an argument I think.

Server log (using StringArgument): 
![image](https://user-images.githubusercontent.com/42968178/49459373-2f715100-f7ef-11e8-86ac-bc3773bf5a0c.png)

**My code**
This code reproduces the behavior:
```java
        LinkedHashMap<String, Argument> arguments = new LinkedHashMap<>();
        arguments.put("test", new StringArgument());
        arguments.put("name", dynamicArgs);
        CommandAPI.getInstance().register("test", CommandPermission.OP, arguments, (sender, args) -> {
            //blablabla
        });
```

Here dynamicArgs is the dynamic argument.

**Comment by JorelAli** [comment]
Yup. Can confirm there was a bug in the code when the Dynamic suggested strings are registered AFTER another argument. This may also relate to the issue with #30.

This has been resolved in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/2b8eb74920c84f5156cef12a62425e2d457adcc7)
