### ISSUE TITLE
[Critical] CommandAPI breaks with latest Spigot update

### ISSUE THREAD

**Issue by HielkePlugins** [JorelAli/1.13-Command-API#36]
**Describe the bug**
After updating spigot to it's latest 1.13.2 version, every API command I try to run throws a NoSuchMethodException. Looks like spigot changed something you're working with?

**Screenshots**
Spigot version:
![image](https://user-images.githubusercontent.com/42968178/50492717-8bf41480-0a19-11e9-8e27-25c6588e1572.png)

Console ouput:
![image](https://user-images.githubusercontent.com/42968178/50492677-4e8f8700-0a19-11e9-9920-402a3b718def.png)
(Here I'm using the /random command I made, but it throws the error with ANY commandAPI command)

I'm using the unreleased 1.8 CommandAPI, because it has some bug fixes I really need. 
This bug however also occurs on 1.7.2.

**Comment by JorelAli** [comment]
I've fixed the issue for the unreleased version of 1.8. You can grab a copy of a pre-built unreleased 1.8 build here:
https://github.com/JorelAli/1.13-Command-API/tree/master/1.13CommandAPI/unreleased%20builds

**Comment by HielkePlugins** [comment]
Thanks for fixing this so fast 👍 
Also I suggest posting a new release soon, as the latest release doesn't work on the latest spigot version.

**Comment by JorelAli** [comment]
I agree... 
It's been difficult lately - the master repo is in a bit of a state and of course, it's been the Christmas period and everyone's busy. On top of that, the 1.8 documentation has yet to be written and I still have bugs and areas I have yet to research.
