### ISSUE TITLE
PlayerArgument causes exception when target player does not exist

### ISSUE THREAD

**Issue by Draycia** [JorelAli/1.13-Command-API#37]
**Describe the bug**
Running `/afk S` when player `S` isn't online calls the CommandExecutor and causes `CommandSyntaxException: That player does not exist` to be thrown when the argument is accessed.

https://pastebin.com/hG4bGKR3

**My code**
This code reproduces the behavior:
```kotlin
    private fun runPlayer(sender: CommandSender, args: Array<out Any>) {
        if (args[0] !is Player) return;
        val player = args[0] as Player; // Exception when reaching this line
    }

    fun registerCommand() {
        val arguments = LinkedHashMap<String, Argument>();
        arguments["afk"] = PlayerArgument().withPermission(CommandPermission.fromString("redacted"));
        CommandAPI.getInstance().register("afk", CommandPermission.fromString("redacted"), arguments, ::runPlayer);
    }
```

**Expected behavior**
Function doesn't run and user is told the argument is invalid.

**Comment by JorelAli** [comment]
Issue fixed in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/c0a15ca85de1f21625aeda227fed56859d016253). Will be included in the next release.
