### ISSUE TITLE
Block location argument

### ISSUE THREAD

**Issue by HielkePlugins** [JorelAli/1.13-Command-API#38]
Vanilla seems to use 2 different type of location argument: a block location one, and the other one (That we have in the CommandAPI)

Vanilla command /setblock uses the first one:
![2019-01-01_18 09 49](https://user-images.githubusercontent.com/42968178/50574833-92ef9e00-0df0-11e9-9ae5-59235b1bb8cb.png)

And /tp uses the other one:
![2019-01-01_18 11 36](https://user-images.githubusercontent.com/42968178/50574841-b6b2e400-0df0-11e9-9003-481b139d190f.png)

As you can see in the screenshots above, the /setblock command actually targets the block that has been selected, while the /tp one gets the location where I select the block. 
(Which is on the top, so the y coordinate is 71 instead of 70)

Because I'm working on a command where you need to target blocks, it's quite annoying if the location isn't right. That's why I suggest an argument to match the one used in /setblock.

It doesn't have to be a completely new argument, It can also be for example a parameter you give with the location argument.

**Comment by JorelAli** [comment]
Added a parameter to the `LocationArgument` to accept a `LocationType`: `BLOCK_POSITION` or `PRECISE_POSITION` in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/26d5e7675d499090434718f491f9ce4d39a23fc5). Thanks for this, I was always wondering why vanilla had two implementations which both seemed to do the same thing
