### ISSUE TITLE
maven repo and don't know what to import

### ISSUE THREAD

**Issue by reventcake295** [JorelAli/1.13-Command-API#44]
I have a few problems with the api because somehow maven won't add the api to the external libraries list and i am using this in my pom.xml
```
<repository>
            <id>mccommandapi</id>
            <url>https://raw.githubusercontent.com/JorelAli/1.13-Command-API/mvn-repo/1.13CommandAPI/</url>
</repository>
```
```
<dependency>
            <groupId>io.github.jorelali</groupId>
            <artifactId>jorelali</artifactId>
            <version>1.8.2</version>
</dependency>
```
and i do not know what to import for Argument is it a CommandAPI object that i am not seeing because of the fact that the plugin isn't loaded as a external libary or is it something else?

I am sorry for my English because it isn't my birth language

**Comment by JorelAli** [comment]
I believe the Maven repository is down at the moment - I'll try and get it up and running as soon as I can.

**Comment by JorelAli** [comment]
I have confirmed that the Maven repository is working as follows.

To add the API to the repository, you want to have a pom.xml that looks something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>GROUP_ID</groupId>
    <artifactId>ARTIFACT_ID</artifactId>
    <version>1.0-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>mccommandapi</id>
            <url>https://raw.githubusercontent.com/JorelAli/1.13-Command-API/mvn-repo/1.13CommandAPI/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.github.jorelali</groupId>
            <artifactId>commandapi</artifactId>
            <version>1.8.2</version>
        </dependency>
    </dependencies>
</project>
```

After adding that to the pom.xml file, you can run `mvn install` to download the API.

The import you're looking for is `io.github.jorelali.commandapi.api.*` for the main API, and `io.github.jorelali.commandapi.api.arguments.*` for the arguments

**Comment by reventcake295** [comment]
thanks that worked now i can start to refactor all the commands for my server!

**Comment by iFallUpHill** [comment]
@JorelAli Is the Maven repo down again? Getting a 404.

**Comment by JorelAli** [comment]
> @JorelAli Is the Maven repo down again? Getting a 404.
> 
> ```
> [WARNING] The POM for io.github.jorelali:commandapi:jar:2.0.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
> ```

I've tried accessing the repository using the following `pom.xml` file as of today (19th June):

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>CmdAPITest</groupId>
  <artifactId>CmdAPITest</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <repositories>
      <repository>
          <id>mccommandapi</id>
          <url>https://raw.githubusercontent.com/JorelAli/1.13-Command-API/mvn-repo/1.13CommandAPI/</url>
      </repository>
  </repositories>

  <dependencies>
      <dependency>
          <groupId>io.github.jorelali</groupId>
          <artifactId>commandapi</artifactId>
          <version>2.0.1</version>
      </dependency>
  </dependencies>
  
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

And my installation of eclipse was able to download the commandapi-2.0.1.jar file successfully with no problems.
