### ISSUE TITLE
Update Maven repo to use new CommandAPI jar which fixes Brigadier dependancies

### ISSUE THREAD

**Issue by i509VCB** [JorelAli/1.13-Command-API#52]
Hello, I did see you've updated CommandAPI to fix the import brigadier issues with this fix: https://github.com/JorelAli/1.13-Command-API/commit/af1911e8e6a9d9765838060e25b3d2dcd44aafb7.

Though this change has not been reflected on the maven repo, could you update the CommandAPI jar within the repo?

**Comment by JorelAli** [comment]
Released version 2.0.1 which contains this change:
https://github.com/JorelAli/1.13-Command-API/releases/tag/v2.0.1
