### ISSUE TITLE
Add section to documentation to use Gradle

### ISSUE THREAD

**Issue by i509VCB** [JorelAli/1.13-Command-API#53]
I think the documentation could benefit from having a section on how to use this API with Gradle

I've given you the required gradle code below and a pointer on how to describe it in documentation:

**Add these to your build.gradle:**

Add this to your repositories:
```
repositories {
    maven {
    	name = 'mccommandapi'
    	url = 'https://raw.githubusercontent.com/JorelAli/1.13-Command-API/mvn-repo/1.13CommandAPI/'
    }
}
```

Add this to your dependencies so the project can build successfully:
```
dependencies {
    compile "io.github.jorelali:commandapi:2.0.1"
}

**Comment by JorelAli** [comment]
I'm not a major fan of Gradle and have very little idea on how to use it. The official documentation on how to create a Bukkit plugin _[here](https://bukkit.gamepedia.com/Plugin_Tutorial)_ gives instructions on how to set up a maven project to manage the dependencies for Bukkit plugins.

I'd be taking a risk in implementing documentation for Gradle, as if anyone comes to me with queries, I'll be basically helpless. I'd rather not be totally helpless if and when it comes to such a situation.

**Comment by i509VCB** [comment]
Well I do understand why you wouldn't want to risk documentation you are clueless about. Really the Gradle dependencies can implement maven. Maybe I could make an article on how to convert Maven POM references to Gradle on spigot forums and just link them to it?

**Comment by JorelAli** [comment]
You know what, I'll take it as a learning opportunity. If someone gets stuck, I'll figure out how to use Gradle right there and then.

![image](https://user-images.githubusercontent.com/4613171/58600341-30ee7400-827c-11e9-9070-09ec4f90e559.png)

**Comment by i509VCB** [comment]
If you do get lost don't mind forwarding them to me.
