### ISSUE TITLE
[Documentation Error] Documentation Changelog

### ISSUE THREAD

**Issue by i509VCB** [JorelAli/1.13-Command-API#54]
At Documentation Changelog, the link to CustomArgument goes to https://jorelali.github.io/1.13-Command-API/customarguments.md which does not exist.

**Proposed fix**
Should be changed to https://jorelali.github.io/1.13-Command-API/customarguments.html

**Comment by JorelAli** [comment]
Fixed in https://github.com/JorelAli/1.13-Command-API/commit/d950492582f5624b430d14ae67ef98b050844063 .
