### ISSUE TITLE
Why there is no support to v1_13_R1

### ISSUE THREAD

**Issue by portlek** [JorelAli/1.13-Command-API#62]
I've just look at the 1.13.jar and i saw the brigadier lib. Why command api does not support to 1.13?

**Comment by JorelAli** [comment]
Basically, when I first implemented the CommandAPI, 1.13.2 was out and was the easiest thing to implement at the time. Since I've now got a much better versioning system, it's definitely possible to add support for 1.13 and 1.13.1.

**Comment by JorelAli** [comment]
Support for 1.13 and 1.13.1 have been included in #64
