### ISSUE TITLE
Api doen't work with NONE Permission

### ISSUE THREAD

**Issue by portlek** [JorelAli/1.13-Command-API#66]
I tried this command;
```java
@Override
public void onEnable() {
    // Plugin startup logic
    final LinkedHashMap<String, Argument> args = new LinkedHashMap<>();
    args.put("player-name", new PlayerArgument());
    args.put("message-text", new GreedyStringArgument());

    CommandAPI.getInstance().register("messageSend", args, (commandSender, objects) -> {
        final Player player = (Player) objects[0];
        final String message = (String) objects[1];
        player.sendMessage(ChatColor.translateAlternateColorCodes('&', message));
    });
}
```
And console output like that;
```
[CommandAPI] Loading CommandAPI v2.2
[CommandAPI] Hooked into NMS Version 14 rev 1 (compatible with 1.14, 1.14.1, 1.14.2, 1.14.3, 1.14.4)
[Debug] Loading Debug v1.0-SNAPSHOT
[CommandAPI] Enabling CommandAPI v2.2
[Debug] Enabling Debug v1.0-SNAPSHOT
[CommandAPI] Registering command /messageSend <PlayerArgument> <GreedyStringArgument> 
Server permissions file permissions.yml is empty, ignoring it
CONSOLE: Reload complete.
[CommandAPI] Linking permissions to commands:
[CommandAPI] NONE -> /messagesend
```
So, i tried to use /messageSend myName <messages...>
And in game;
![alt text](https://i.snag.gy/TD7XFg.jpg)

**Comment by portlek** [comment]
Also, i tried;
CommandPermission.fromString("debug.command.sendmessage")
When I register the command and I installed groupmanager then I give the permission but result is same.
When use the command, it's work but the suggestions don't work.

**Comment by JorelAli** [comment]
After my initial testing, I have not been able to confirm that the NONE permission doesn't work.

When using the following code:
```java
LinkedHashMap<String, Argument> args = new LinkedHashMap<>();
args.put("player-name", new PlayerArgument());
args.put("message-text", new GreedyStringArgument());

CommandAPI.getInstance().register("messageSend", args, (commandSender, objects) -> {
    final Player player = (Player) objects[0];
    final String message = (String) objects[1];
    player.sendMessage(ChatColor.translateAlternateColorCodes('&', message));
});
```
On a server with no permission system, it worked fine when not being OP.
After installing groupmanager, it worked fine when not being OP.

Perhaps it depends on your Minecraft version? The tests I did were on Minecraft 1.14.4 using CommandAPI version 2.2.
-----

However, `CommandPermission.fromString("debug.command.sendmessage")` not working is indeed a bug that needs to be addressed.
