### ISSUE TITLE
[Question] Is there a way to add a prefix to the command?

### ISSUE THREAD

**Issue by Minenash** [JorelAli/1.13-Command-API#70]
Example:
`/pluginName:testCommand`

**Comment by JorelAli** [comment]
Good question.
I'll look into it.

**Comment by JorelAli** [comment]
Yes, you can. The CommandAPI automatically supports it, for example:

```java
CommandAPI.getInstance().register("pluginname:testcommand", new LinkedHashMap<>(), (sender, args) -> {
    //Whatever
});       
```

After doing a quick look around, as long as it conforms to the Minecraft Namespaced Key, it shouldn't have any problems (but I cannot confirm this claim with 100% certainty. If and when I do, I'll make sure to state it in the documentation, this is a pretty important find!): 

According to the Bukkit documentation: _"Namespaces may only contain lowercase alphanumeric characters, periods, underscores, and hyphens. Keys may only contain lowercase alphanumeric characters, periods, underscores, hyphens, and forward slashes."_

**Comment by Minenash** [comment]
too bad we can't get rid of the `minecraft:` But I understand :P Thanks for responding to these really quickly : )

**Comment by JorelAli** [comment]
Reloading will never be a feature the CommandAPI will support. Ever.
If the CommandAPI chooses to use the NBT API (which is looking pretty probable now), the NBT API specifically states for its latest version _**not**_ to use the reload feature.
