### ISSUE TITLE
[Bug] Old Documentation's Table of Contents's links do not work? 

### ISSUE THREAD

**Issue by Minenash** [JorelAli/1.13-Command-API#71]
**CommandAPI version / Describe the bug**
Forever, as all the pre-seperate-site docs had there links go to the master branch, so if someone opened the 1.7 docs, and click a link in the ToC, then it went to the latest docs. Now that the docs are in a "seperate site", the links goto a page that no longer exists.

**My code**
N/A

**Expected behavior**
ToC links to link to their own docs

**Screenshots**
N/A

**Additional context**
Sorry for all the issues :P

**Comment by JorelAli** [comment]
That is indeed correct. Will fix when I get round to it. At the moment, resolving the bugs with the CommandAPI's functionality is of a higher priority.
