### ISSUE TITLE
Better itemslots

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/1.13-Command-API#77]
**Please describe your suggestion**
A better form of handling item slots, instead of using integers.

The `ItemSlotArgument` currently returns an integer, which indicates the slot number. This slot number is a little bit unintuitive however, since slots _(across Bukkit and the MinecraftWiki)_ are inconsistent between Bukkit and NMS.

-----

To illustrate this point, take the documentation for the `setItem` method from the Bukkit `PlayerInventory` interface:

> Stores the ItemStack at the given index of the inventory.
Indexes 0 through 8 refer to the hotbar. 9 through 35 refer to the main inventory, counting up from 9 at the top left corner of the inventory, moving to the right, and moving to the row below it back on the left side when it reaches the end of the row. It follows the same path in the inventory like you would read a book.
> 
> Indexes 36 through 39 refer to the armor slots. Though you can set armor with this method using these indexes, you are encouraged to use the provided methods for those slots.
> 
> Index 40 refers to the off hand (shield) item slot. Though you can set off hand with this method using this index, you are encouraged to use the provided method for this slot.
> 
> If you attempt to use this method with an index less than 0 or greater than 40, an ArrayIndexOutOfBounds exception will be thrown.

In Bukkit's standard, indexes 36-39 are the armor slots, and index 40 is the offhand item. However, the `ItemSlotArgument` produces numbers according to the NMS standard, which is described in [this file](https://github.com/JorelAli/1.13-Command-API/blob/3.0-release/item%20slot%20mappings.txt) and partially using this image:
![image](https://user-images.githubusercontent.com/4613171/63952449-89016600-ca77-11e9-8c44-d13c1c4aba5a.png)

In the NMS standard, you would intuitively select `armor.chest` to indicate a player's chestplate slot, however this returns the index 102, which is not defined for Bukkit.

-----

I'm really just looking for suggestions of how to overcome this issue, since the easiest method so far is to simply remove this argument and not include it in the CommandAPI.

@Minenash
@i509VCB

**Comment by Minenash** [comment]
Okay, so I think the best way we can do this is create a wrapper which stores the raw nms value, and a ContainerType, and an index for types like container and enderchest. If I remember correctly bukkit inventory stuff works on ids of 0-N on per container. This is the code I've written for the wrapper.
Note: Container.0-8 and Hotbar.0-8 return the same nms value, and so does Container.9-35 and Inventory.0-27.

```java

public class ItemSlot {

	enum ContainerType {
		ARMOR_FEET, ARMOR_LEGS, ARMOR_CHEST, ARMOR_HEAD,
		HORSE_SADDLE, HORSE_ARMOR, HORSE_CHEST,
		WEAPON_MAINHAND,WEAPON_OFFHAND,
		CONTAINER, //Includes Hotbar & Inventory
		ENDERCHEST,
		HORSE,
		VILLAGER
	}
	
	private final int rawNMSID, index;
	private final ContainerType containerType;
	
	public ItemSlot(int id) {
		rawNMSID = id;

		if (id >= 0 && id <= 53) {
			containerType = ContainerType.CONTAINER;
			index = id;
		}
		else if (id >= 200 && id <= 266) {
			containerType = ContainerType.ENDERCHEST;
			index = id - 200;
		}
		else if (id >= 300 && id <= 307) {
			containerType = ContainerType.VILLAGER;
			index = id - 300;
		}
		else if (id >= 500 && id <= 514) {
			containerType = ContainerType.HORSE;
			index = id - 500;
		}
		else {
			index = 0;
			switch (id) {
				case 98:  containerType = ContainerType.WEAPON_MAINHAND; break;
				case 99:  containerType = ContainerType.WEAPON_OFFHAND;  break;
				case 100: containerType = ContainerType.ARMOR_FEET;      break;
				case 101: containerType = ContainerType.ARMOR_LEGS;      break;
				case 102: containerType = ContainerType.ARMOR_CHEST;     break;
				case 103: containerType = ContainerType.ARMOR_HEAD;      break;
				case 400: containerType = ContainerType.HORSE_SADDLE;    break;
				case 401: containerType = ContainerType.HORSE_ARMOR;     break;
				case 399: containerType = ContainerType.HORSE_CHEST;     break;
				default:  containerType = null;
			}
		}
	}

	public ContainerType getContainerType() {
		return containerType;
	}

	public int getRawNMSID() {
		return rawNMSID;
	}

	public int getIndex() {
		return index;
	}
	
}
```
The enum should be in it's own file, so devs don't have to do `ItemSlot.ContainerType.ARMOR_CHEST`

**Comment by JorelAli** [comment]
Yes, using an enum would appear to resolve the issue. I don't think exposing the raw NMS id is a good choice, but using an enum will definitely be the best way as far as I can tell.

**Comment by Minenash** [comment]
I'm going to reply to the comments/notes in the commits, as it spans too, so this might be easier.:

```java
/* Note: Container value 40 still implies offhand btw.
 * Therefore, if index > 35 && CONTAINER, check if
 * inventory is a doublechest!
 */
```
I'm unsure, where 40 = offhand comes from. I just tested, and anything over `container.35`, just failed on the player.

```java
//TODO: Test this. If we open an enderchest and dump something
//in slot #0, are we SURE it doesn't just dump it in the left
//most bottom corner (first hotbar item)?
```
Can you reword/elaborate on this, I'm not really sure what your asking.

```java
//Also, what even is this?
```(refering to the slot `horse.chest`)
From my testing, the only item it can be set to is a Chest. And when it is set to such, the mules who got the slot set, now has the chest. I'm assuming it supports NBT, allowing it to set the internals of a horse. This is also strengthened by not having a horse slot type, and container/inventory/hotbar does not work on mules.

**Comment by JorelAli** [comment]
> Index 40 refers to the off hand (shield) item slot. Though you can set off hand with this method using this index, you are encouraged to use the provided method for this slot.

Say you open a player's inventory and use `ContainerType.CONTAINER` and the value is 40 then you're setting the offhand instead of a "40th slot". You just need to ensure that developers have _the right inventory_

**Comment by Minenash** [comment]
If we do the method of applying it to a inventory type, then that would have to be as a method, not on argument built.

Though, while container does overlap with inv, and map to the same thing in game, I feel like giving the dev what we have now is fine. They know if it's a chest or player, and can set accordingly. But also that 40 is only from Bukkit, Players wouldn't use container 40 to set it, they would use weapon.offhand. basically I think this is something better left to the devs

**Comment by JorelAli** [comment]
> They know if it's a chest or player, and can set accordingly.

Not true. Providing the plain `ItemSlotArgument` doesn't let them only choose a specific thing. The point of the `ItemSlotArgument` is to provide a command sender with the selection of _any_ item slot - for example, the developer could intend it to be solely an inventory container, but it doesn't stop a user from entering `armor.chest`. If you say, make a command designed to only accept a single slot in a chest, there are better alternatives _(e.g. `IntegerArgument(0, 35)`)_, which won't lead to say this:

```java
(sender, args) -> {
    ItemSlot is = args[0];
    if(!is.CONTAINER || is.getIndex() > 35) { sender.sendMessage ("invalid input") }
}
```

One of the main philosophies of the CommandAPI is to basically eliminate all needs for extra checks. For example, instead of say:

```java
onCommand(CommandSender sender, ... , String[] args) {
    if(args[0] instanceof Integer) {
        int i = (int) args[0];
              if(i >= 0 && i <= 35) {
                        //code
            }
    }
    //return error here
}
```

You can just do:

```java
(sender, args) -> {
     int i = (int) args[0]; // Already guaranteed to be an integer and between 0 and 35
}
```

-----

I still think it's not an endeavour that fits what I believe is a suitable argument for the CommandAPI.

**Comment by Minenash** [comment]
(I mean if you truly still don't want to keep it, then by all means remove it, but)

Assuming they set up the command correctly, they _do_ know what inventory it's based off of another argument.

**Comment by JorelAli** [comment]
After a lot of careful consideration, I will not be implementing the ItemSlot argument in CommandAPI's 3.0 release.
