### ISSUE TITLE
[Documentation Error (?)] `Commands can have prefixes` is misleading.

### ISSUE THREAD

**Issue by Minenash** [JorelAli/1.13-Command-API#78]
**File**
Documentation Notes

**Section**
Things to note in the next documentation

**Errata**
Commands can have prefixes such as `a:b`

**Proposed fix**
As found out [here](https://github.com/JorelAli/1.13-Command-API/issues/70#issuecomment-525555831), while you can put `:`s in the command name, that prefix will be required.

**Comment by JorelAli** [comment]
The documentation notes does not in fact affect the formal documentation that is produced at the end of the project, it's just a reference for things to keep track of. The "prefixes" denoted by the : character will not be included in the final result.
