### ISSUE TITLE
Add methods to fail command if sender is not entity/player or registration of Player/EntityCommands

### ISSUE THREAD

**Issue by i509VCB** [JorelAli/1.13-Command-API#81]
A way to fail commands with a one liner would be convent like CommandAPI#failNotPlayer(Command Sender) or CommandAPI#failNotEntity(Command Sender)

But I've thought there could be a better way to handle it. 

Maybe a special register method that instead runs a PlayerCommand or EntityCommand that provides a Player or Entity along with command sender (a new functional interface) and registration with that command type will fail the command if the sender does not meet the requirements.

**Comment by JorelAli** [comment]
Hmm. Here's the draft of what I was about to respond with, but I think I'll plan it out in more detail before I make any decisions. A new functional interface sounds like a good idea and I'll see what I can do.

> ## The one liner approach
> 
> One liner checks could easily be added inside some generic utility class:
> 
> ```java
> Player getPlayer(CommandSender sender) throws WrapperCommandSyntaxException {
>     if(sender instanceof Player) {
>         return (Player) sender;
>     } else {
>         CommandAPI.fail("Sender must be a player");
>     }
> }
> ```
> 
> Allowing you to do something like this:
> 
> ```java
> (args, sender) -> {
>     getPlayer(sender).getLocation() //Or whatever
> }
> ```
> 
> It just comes down to "syntactic sugar" at the end of the day, and this would be the "easiest" option, but not necessarily the best.
> 
> ## A new interface
> 
> Given that the CommandAPI already has the following functional interfaces:
> ```
> @FunctionalInterface
> public interface ResultingCommandExecutor {
> 	int run(CommandSender sender, Object[] args) throws WrapperCommandSyntaxException;
> }
> 
> @FunctionalInterface
> public interface CommandExecutor {
> 	void run(CommandSender sender, Object[] args) throws WrapperCommandSyntaxException;
> }
> ```
> 
> And the fact that the register methods are pretty poorly implemented, I think this is probably the best > way to go, and rewrite the registration methods. You've got to remember that this project is over a > year old, and I've definitely learnt some things in the past year and looking back at this code, I have no > idea why certain (poor) design choices were made.

**Comment by i509VCB** [comment]
A new interface could make sense but having the same amount arguments would be a vague outcome in compiler. 

So either an option in register method (weather it is two booleans specifying entity and player or an enum type) could be an option. 

Also maybe a class filled with constant exception types (using Translatable Text

**Comment by JorelAli** [comment]
Issue resolved in pull request #83.

Translatable Text won't quite work _exactly_ how you'd expect. As stated by the [Chat Component API page](https://www.spigotmc.org/wiki/the-chat-component-api/):

> It can be used to send translation keys for the client translate client side, this means you are limited to the text provided by Minecraft (see here) unless a resource pack is used to add more.

I plan to let you change the error message in the CommandAPI configuration (when I get round to it).
