### ISSUE TITLE
Move inner classes to the bottom of their containing classes

### ISSUE THREAD

**Issue by ZiluckMichael** [JorelAli/1.13-Command-API#82]
It is a bad practice to keep inner classes at the top or other arbitrary locations within their parent class. Based on every formatting guide I can find online, it says to keep them at the bottom of the class.

Please reformat this to make everything significantly easier to understand.

**Comment by JorelAli** [comment]
Acknowledged.

**Comment by ZiluckMichael** [comment]
Oh wow, I didn't expect you to get to this that fast. Thanks mate!
