### ISSUE TITLE
Allowing multiple executers to be used on the same command

### ISSUE THREAD

**Issue by Minenash** [JorelAli/1.13-Command-API#87]
**Please describe your suggestion**
Now that `.executesPlayer()`, `.executesEntity()` and `.executesCommandBlock()` exists, it might be beneficial to allow more than one of these at a time. I say might, because, it might not be easier than just doing a check of what it is within the normal `.executes()`. If there's a player executor and a entity executor, but no commandblock executor, and a cmdb runs the command, it'd still automatically fail, like the current implementation.

**Please supply examples of the desired inputs and outputs**
_Example:_
```java
new CommandAPICommand("cmd")
    .executesPlayer((sender, args) -> {
        Bukkit.getServer().broadcastMessage("A player ran the test command.");
    });
   .executesCommandBlock((sender, args) -> {
        Bukkit.getServer().broadcastMessage("A command block ran the test command.");
    });
```
***
and yes, I've seen your notice about v3.0

**Comment by JorelAli** [comment]
I've thought about this as well. The way the CommandAPI is set up currently, it's not as trivial to add it, but I do want to add it at some point in time.
