### ISSUE TITLE
Float and Double arguments take integer minimum and maximums

### ISSUE THREAD

**Issue by SHsuperCM** [JorelAli/1.13-Command-API#92]
**CommandAPI version**
2.3

**Minecraft version**
1.14.4

**Describe the bug**
The minimum/maximum for these arguments do not allow for values with specific decimal requirements. (you cannot do a minimum of 0.001 for example)

**My code**
This code reproduces the behavior:
```java
new FloatArgument(0.001f);
new DoubleArgument(0.001d);
```

**Expected behavior**
I expected to be allowed to use places after the decimal point when validating arguments.

**Comment by JorelAli** [comment]
Apologies - issue has been fixed in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/d11fa87c745c65b40f77667fed1f878beeb98aa5).
