### ISSUE TITLE
getMainScoreboard() will return null when onLoad()

### ISSUE THREAD

**Issue by aianlinb** [JorelAli/1.13-Command-API#94]
**CommandAPI version**
v2.3

**Minecraft version**
1.15.2

**Describe the bug**
getMainScoreboard() will return null when onLoad()

**Additional context**
java.lang.NullPointerException: null
	at io.github.jorelali.commandapi.api.arguments.DefinedCustomArguments.objectiveArgument(DefinedCustomArguments.java:13)
	at myPlugin.onLoad(myPlugin:line)

**Comment by JorelAli** [comment]
Thanks for bringing this up - it's likely due to the Bukkit scoreboard not being initialized so early on in the plugin loading process. I'll make sure that this issue is resolved before releasing version 3.0.

**Comment by JorelAli** [comment]
Issue fixed for version 3.0 - I changed the return type of Objectives and Teams to Strings, so developers can retrieve the objectives and teams manually whenever the command is run.
