### ISSUE TITLE
Dynamic Suggestions based on context

### ISSUE THREAD

**Issue by Ricky12Awesome** [JorelAli/1.13-Command-API#99]
A dynamic suggestion that will suggest different things depending on input from previous arguments

**Example:**:
`/test 1` gives `a` as the next suggestion
`/test 2` gives `b` as the next suggestion
`/test 3` gives `c` as the next suggestion

```kotlin
val dynamic0 = DynamicSuggestedStringArgument(DynamicSuggestions {
  arrayOf("1", "2", "3") // Pretend this is dynamic data
})

val dynamic1 = DynamicSuggestedStringArgument(DynamicSuggestions {
  // Maybe make args as part of the params like sender
  val args = arrayOf("2")

  when (args[0]) {
    "1" -> arrayOf("a")
    "2" -> arrayOf("b")
    "3" -> arrayOf("c")
    else -> arrayOf("")
  }
})
```

**Use Cases**
Let's say you want to suggest something like `Map<String, Map<String, Value>>` and only want to display things for that key

For example:
```kotlin
val map = mapOf<String, Map<String, Value>>()

val name = DynamicSuggestedStringArgument(DynamicSuggestions {
  map.keys.toTypeArray()
})

val ofName = DynamicSuggestedStringArgument(DynamicSuggestions { args ->
  map[args[0]]?.keys?.toTypeArray() ?: arrrayOf()
})
```

**Comment by JorelAli** [comment]
That's an interesting idea indeed - I quote like it. Given the current state of the project, I don't think this will make an appearance in the 3.0 release, but I am heavily considering adding it as a feature for the future.

With the way the new API is constructed, this shouldn't be too difficult to add!

**Comment by JorelAli** [comment]
Commit 9951f8f adds full support for having an argument with the context of its previously declared arguments.

Here's the Java code used to test our your idea. I decided to keep its style near-identical to registering a normal command executor:
```java
LinkedHashMap<String, Argument> arguments = new LinkedHashMap<>();
arguments.put("number", new IntegerArgument());
arguments.put("extra", new StringArgument().overrideSuggestions((sender, args) -> {
	int number = (int) args[0];
	
	switch(number) {
	case 1:
		return new String[] {"a"};
	case 2:
		return new String[] {"b"};
	case 3:
		return new String[] {"c"};
	}
	return new String[] {};
}));

new CommandAPICommand("test").withArguments(arguments)
.executes((sender, args) -> {
	System.out.println(Arrays.deepToString(args));
}).register();
```

Here's a gif of it working in action:
![GIF](https://user-images.githubusercontent.com/4613171/85928506-4b42b900-b8a5-11ea-9445-d3065bff1788.gif)

Once again, thanks for the suggestion - I really like this one, it looks pretty cool!
